{{- if .Values.operatorRoleBinding.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.operatorNamespace.name }}
  name: {{ .Values.operatorRoleBinding.name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.operatorNamespace.name }}
  name: {{ .Values.operatorServiceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.operatorRole.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
