{{- if .Values.operatorServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.operatorNamespace.name }}
  name: {{ .Values.operatorServiceAccount.name }}
{{- end }}
